set_property PACKAGE_PIN  AN9  [ get_ports "c0_ddr4_adr[0]" ]
set_property PACKAGE_PIN  AN6  [ get_ports "c0_ddr4_adr[1]" ]
set_property PACKAGE_PIN  AN7  [ get_ports "c0_ddr4_adr[2]" ]
set_property PACKAGE_PIN  AP5  [ get_ports "c0_ddr4_adr[3]" ]
set_property PACKAGE_PIN  AK8  [ get_ports "c0_ddr4_adr[4]" ]
set_property PACKAGE_PIN  AP7  [ get_ports "c0_ddr4_adr[5]" ]
set_property PACKAGE_PIN  AM10 [ get_ports "c0_ddr4_adr[6]" ]
set_property PACKAGE_PIN  AN8  [ get_ports "c0_ddr4_adr[7]" ]
set_property PACKAGE_PIN  AK7  [ get_ports "c0_ddr4_adr[8]" ]
set_property PACKAGE_PIN  AP10 [ get_ports "c0_ddr4_adr[9]" ]
set_property PACKAGE_PIN  AM6  [ get_ports "c0_ddr4_adr[10]" ]
set_property PACKAGE_PIN  AM8  [ get_ports "c0_ddr4_adr[11]" ]
set_property PACKAGE_PIN  AP4  [ get_ports "c0_ddr4_adr[12]" ]
set_property PACKAGE_PIN  AP8  [ get_ports "c0_ddr4_adr[13]" ]
set_property PACKAGE_PIN  AJ9  [ get_ports "c0_ddr4_adr[14]" ]
set_property PACKAGE_PIN  AP6 [ get_ports "c0_ddr4_adr[15]" ]
set_property PACKAGE_PIN  AP11  [ get_ports "c0_ddr4_adr[16]" ]


set_property PACKAGE_PIN  AJ10 [ get_ports "c0_ddr4_ba[0]" ]
set_property PACKAGE_PIN  AP9  [ get_ports "c0_ddr4_ba[1]" ]
set_property PACKAGE_PIN  AL10 [ get_ports "c0_ddr4_bg[0]" ]
set_property PACKAGE_PIN  AL6  [ get_ports "c0_ddr4_ck_t[0]" ]
set_property PACKAGE_PIN  AL5  [ get_ports "c0_ddr4_ck_c[0]" ]
set_property PACKAGE_PIN  AK10 [ get_ports "c0_ddr4_cke[0]" ]
set_property PACKAGE_PIN  AM9  [ get_ports "c0_ddr4_act_n" ]
set_property PACKAGE_PIN  AM5  [ get_ports "c0_ddr4_reset_n" ]
set_property PACKAGE_PIN  AK9  [ get_ports "c0_ddr4_odt[0]" ]
set_property PACKAGE_PIN  AN4 [ get_ports "c0_ddr4_cs_n[0]" ]

set_property PACKAGE_PIN AH2 [ get_ports "c0_ddr4_dm_n[0]" ]
set_property PACKAGE_PIN AH1 [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property PACKAGE_PIN AJ1 [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property PACKAGE_PIN AE2 [ get_ports "c0_ddr4_dq[0]" ]
set_property PACKAGE_PIN AG3 [ get_ports "c0_ddr4_dq[1]" ]
set_property PACKAGE_PIN AD1 [ get_ports "c0_ddr4_dq[2]" ]
set_property PACKAGE_PIN AF2 [ get_ports "c0_ddr4_dq[3]" ]
set_property PACKAGE_PIN AD2 [ get_ports "c0_ddr4_dq[4]" ]
set_property PACKAGE_PIN AH3 [ get_ports "c0_ddr4_dq[5]" ]
set_property PACKAGE_PIN AE1 [ get_ports "c0_ddr4_dq[6]" ]
set_property PACKAGE_PIN AF1 [ get_ports "c0_ddr4_dq[7]" ]


set_property PACKAGE_PIN AE5 [ get_ports "c0_ddr4_dm_n[1]" ]
set_property PACKAGE_PIN AJ6 [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property PACKAGE_PIN AJ5 [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property PACKAGE_PIN AE3 [ get_ports "c0_ddr4_dq[8]" ]
set_property PACKAGE_PIN AH4 [ get_ports "c0_ddr4_dq[9]" ]
set_property PACKAGE_PIN AD4 [ get_ports "c0_ddr4_dq[10]" ]
set_property PACKAGE_PIN AG4 [ get_ports "c0_ddr4_dq[11]" ]
set_property PACKAGE_PIN AE4 [ get_ports "c0_ddr4_dq[12]" ]
set_property PACKAGE_PIN AG5 [ get_ports "c0_ddr4_dq[13]" ]
set_property PACKAGE_PIN AF3 [ get_ports "c0_ddr4_dq[14]" ]
set_property PACKAGE_PIN AJ4 [ get_ports "c0_ddr4_dq[15]" ]

set_property PACKAGE_PIN AH7 [ get_ports "c0_ddr4_dm_n[2]" ]
set_property PACKAGE_PIN AE8 [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property PACKAGE_PIN AF8 [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property PACKAGE_PIN AD6 [ get_ports "c0_ddr4_dq[16]" ]
set_property PACKAGE_PIN AG8 [ get_ports "c0_ddr4_dq[17]" ]
set_property PACKAGE_PIN AF6 [ get_ports "c0_ddr4_dq[18]" ]
set_property PACKAGE_PIN AF7 [ get_ports "c0_ddr4_dq[19]" ]
set_property PACKAGE_PIN AD7 [ get_ports "c0_ddr4_dq[20]" ]
set_property PACKAGE_PIN AH8 [ get_ports "c0_ddr4_dq[21]" ]
set_property PACKAGE_PIN AE7 [ get_ports "c0_ddr4_dq[22]" ]
set_property PACKAGE_PIN AG6 [ get_ports "c0_ddr4_dq[23]" ]

set_property PACKAGE_PIN AE10 [ get_ports "c0_ddr4_dm_n[3]" ]
set_property PACKAGE_PIN AF11 [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property PACKAGE_PIN AG11 [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property PACKAGE_PIN AE12 [ get_ports "c0_ddr4_dq[24]" ]
set_property PACKAGE_PIN AG9	[ get_ports "c0_ddr4_dq[25]" ]
set_property PACKAGE_PIN AH11 [ get_ports "c0_ddr4_dq[26]" ]
set_property PACKAGE_PIN AE9 [ get_ports "c0_ddr4_dq[27]" ]
set_property PACKAGE_PIN AH12 [ get_ports "c0_ddr4_dq[28]" ]
set_property PACKAGE_PIN AG10 [ get_ports "c0_ddr4_dq[29]" ]
set_property PACKAGE_PIN AF12	[ get_ports "c0_ddr4_dq[30]" ]
set_property PACKAGE_PIN AD10 [ get_ports "c0_ddr4_dq[31]" ]

set_property INTERNAL_VREF 0.6 [get_iobanks 65]



